import struct, os, glob
def be16(b,o): return (b[o]<<8)|b[o+1]
def be32(b,o): return (b[o]<<24)|(b[o+1]<<16)|(b[o+2]<<8)|b[o+3]
def img_size(b):
    e_phoff=be32(b,0x1C); e_shoff=be32(b,0x20)
    e_phentsize=be16(b,0x2A); e_phnum=be16(b,0x2C)
    e_shentsize=be16(b,0x2E); e_shnum=be16(b,0x30)
    end=e_shoff+e_shnum*e_shentsize
    for k in range(e_phnum):
        po=e_phoff+k*e_phentsize
        if po+0x14>len(b): break
        end=max(end, be32(b,po+0x04)+be32(b,po+0x10))
    for k in range(e_shnum):
        so=e_shoff+k*e_shentsize
        if so+0x18>len(b): break
        if be32(b,so+0x04)!=8: end=max(end, be32(b,so+0x10)+be32(b,so+0x14))
    return min(end,len(b))
def fnv(b):
    h=1469598103934665603
    for x in b: h=((h^x)*1099511628211)&0xFFFFFFFFFFFFFFFF
    return h

imgs=[]
for f in sorted(glob.glob("spu/*.elf")):
    img=os.path.splitext(os.path.basename(f))[0]
    b=open(f,'rb').read(); sz=img_size(b)
    imgs.append((img, fnv(b[:sz]), be32(b,0x18)))

L=[]
L.append('/* ydkj_spu_workloads.c - GENERATED by tools/gen_spu_workloads.py.')
L.append(' * Registers the title\'s 22 lifted SPU images with the workload dispatch')
L.append(' * registry (by FNV-1a-64 image fingerprint) and populates each image\'s')
L.append(' * indirect-branch table under a distinct image id. cellSpurs AddWorkload/')
L.append(' * CreateTask call spu_workload_dispatch(), which fingerprints the guest')
L.append(' * image, finds the lifted entry here, and runs it on a fresh local store. */')
L.append('#include "../../runtime/spu/spu_workload.h"')
L.append('')
L.append('extern void spu_begin_image(int image_id);')
L.append('')
L.append('/* per-image extern decls (prefixed entry fn + recomp_register) */')
for i,(img,fp,ent) in enumerate(imgs,1):
    L.append(f'extern void {img}_spu_func_{ent:08X}(spu_context*);')
    L.append(f'extern void {img}_spu_recomp_register(void);')
L.append('')
L.append('void ydkj_spu_register_all(void)')
L.append('{')
for i,(img,fp,ent) in enumerate(imgs,1):
    L.append(f'    spu_begin_image({i}); {img}_spu_recomp_register();')
    L.append(f'    spu_workload_register_img(0x{fp:016X}ULL, {img}_spu_func_{ent:08X}, {i}, "{img}");')
L.append('    spu_begin_image(0);')
L.append('}')
L.append('')
L.append('/* Auto-register at startup (before the game adds any SPURS workload/task). */')
L.append('__attribute__((constructor)) static void ydkj_spu_autoreg(void)')
L.append('{')
L.append('    ydkj_spu_register_all();')
L.append('}')
open("src/spu_gen/ydkj_spu_workloads.c","w").write("\n".join(L)+"\n")
print("Wrote src/spu_gen/ydkj_spu_workloads.c with", len(imgs), "images")
