#!/usr/bin/env python3
"""SPU workload-dispatch test program.

Exercises runtime/spu/spu_workload.c — the cellSpurs dispatch brick: fingerprint
an SPU image, find its lifted entry, load the ELF into a local store, and run it
with the SPURS task arg in r3.

The SPU program proves the two things the loader+ABI must get right:
  1. LOCAL STORE was loaded from the ELF image — it reads a marker word baked
     into the image at LS 0x80 and forwards it; if the LS were merely zeroed the
     marker would read 0.
  2. r3 (the task/job arg EA) propagated — it forwards r3.
Both are DMA-PUT to main memory so the host harness can check them.

Also emits test_workload_image.h: the exact ELF bytes as a C array plus the
Python-side FNV-1a-64 fingerprint, so the harness validates that the C and
offline fingerprints agree (the offline extractor uses the same hash to build
the registration manifest).
"""
import struct, os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "..", "tools"))
from wrap_spu_elf import wrap

def w(v): return struct.pack(">I", v & 0xFFFFFFFF)
def ri16(op9, i16, rt): return w(((op9 & 0x1FF) << 23) | ((i16 & 0xFFFF) << 7) | (rt & 0x7F))
def ri10(op8, i10, ra, rt): return w(((op8 & 0xFF) << 24) | ((i10 & 0x3FF) << 14) | ((ra & 0x7F) << 7) | (rt & 0x7F))
def rr(op11, rb, ra, rt): return w(((op11 & 0x7FF) << 21) | ((rb & 0x7F) << 14) | ((ra & 0x7F) << 7) | (rt & 0x7F))
def ch(op11, channel, rt): return w(((op11 & 0x7FF) << 21) | ((channel & 0x1F) << 7) | (rt & 0x7F))

IL, LQD, STQD, WRCH, STOP = 0x81, 0x34, 0x24, 0x10D, 0x000
MFC_LSA, MFC_EAH, MFC_EAL, MFC_Size, MFC_TagID, MFC_Cmd = 16, 17, 18, 19, 20, 21
MFC_PUT = 0x20
MARKER = 0xCAFEF00D

# LQD/STQD imm is scaled by 16: byte offset 0x100 -> imm 0x10, 0x80 -> imm 8.
b  = ri16(IL, 0, 0)                # il   r0, 0            (base reg = 0)
b += ri10(LQD, 0x08, 0, 11)       # lqd  r11, 0x80(r0)    r11 = LS[0x80] = marker
b += ri10(STQD, 0x10, 0, 3)       # stqd r3,  0x100(r0)   LS[0x100] = r3 (task arg)
b += ri10(STQD, 0x11, 0, 11)      # stqd r11, 0x110(r0)   LS[0x110] = marker
# --- DMA PUT: LS 0x100..0x11F (32 bytes) -> main memory EA 0 ---
b += ri16(IL, 0x100,    3)        # il   r3, 0x100        (LSA)  [overwrites arg, already stored]
b += ri16(IL, 0,        4)        # il   r4, 0            (EAH)
b += ri16(IL, 0,        5)        # il   r5, 0            (EAL = main-mem offset 0)
b += ri16(IL, 32,       6)        # il   r6, 32           (Size)
b += ri16(IL, 0,        7)        # il   r7, 0            (TagID)
b += ri16(IL, MFC_PUT,  8)        # il   r8, 0x20         (PUT)
b += ch(WRCH, MFC_LSA,   3)
b += ch(WRCH, MFC_EAH,   4)
b += ch(WRCH, MFC_EAL,   5)
b += ch(WRCH, MFC_Size,  6)
b += ch(WRCH, MFC_TagID, 7)
b += ch(WRCH, MFC_Cmd,   8)       # issue PUT (LS -> main memory)
b += rr(STOP, 0, 0, 0)            # stop

# Pad to 0x80 and place the marker word there (baked into the loaded image).
assert len(b) <= 0x80, f"code too long ({len(b)} bytes) to place marker at 0x80"
b = b.ljust(0x80, b"\x00") + struct.pack(">I", MARKER) + b"\x00" * 12

elf = wrap(b, base=0, entry=0, symbols=[{"name": "main", "addr": 0, "size": len(b)}])
open(os.path.join(HERE, "test_workload.elf"), "wb").write(elf)

# FNV-1a-64 over the exact ELF bytes — the canonical workload fingerprint.
def fnv1a64(data):
    h = 1469598103934665603
    for byte in data:
        h ^= byte
        h = (h * 1099511628211) & 0xFFFFFFFFFFFFFFFF
    return h
fp = fnv1a64(elf)

with open(os.path.join(HERE, "test_workload_image.h"), "w") as f:
    f.write("/* Generated by gen_test_workload.py — exact SPU ELF bytes + fingerprint. */\n")
    f.write("#ifndef TEST_WORKLOAD_IMAGE_H\n#define TEST_WORKLOAD_IMAGE_H\n")
    f.write(f"#define kWorkloadElfSize {len(elf)}u\n")
    f.write(f"#define kWorkloadFP 0x{fp:016X}ULL\n")
    f.write(f"#define kWorkloadMarker 0x{MARKER:08X}u\n")
    f.write("static const unsigned char kWorkloadElf[kWorkloadElfSize] = {\n")
    for i in range(0, len(elf), 16):
        f.write("    " + ",".join(f"0x{x:02X}" for x in elf[i:i+16]) + ",\n")
    f.write("};\n#endif\n")

print(f"Wrote test_workload.elf ({len(elf)} bytes ELF, {len(b)} bytes image) fp=0x{fp:016X}")
